### ISSUE TITLE
Lunar year does not begin at spring festival

### ISSUE THREAD

**Issue by sufeiking** [fztransit/Luni-solar-Calendar#1]
For example, in 2022,壬寅年 begins at February 4（春分）, not at February 1（春节）.

**Comment by fztransit** [comment]
我明白你的意思，认为一年应该从节气（立春）而不是春节开始。实际上这是两种计算年起始的方式，并没有谁对谁错的问题。而从春节纪年一直是中国古代官方历书的传统。明清的许多历书被保留下来仍然可以看到（见下链接），它们每年会注记一年的日数，约为354日或384日，显然是从春节计算。
http://read.nlc.cn/allSearch/searchList?searchType=1002&showType=1&pageNo=1&searchWord=%E5%A4%A7%E7%BB%9F%E6%9B%86

**Comment by fztransit** [comment]
如果你想修改为从立春纪年，在PerpetualCalendar.py文件中，找到displayMonth函数，它的入口处（168行）获取了当年的节气信息，存储在列表jqb中。这个列表的行数即月数（0行对应1月），每行存储该月的节气（以[节气日期，节气序]的形式），节气序从冬至起排，立春即为3，找到3对应的月日，并返回。displayDate函数获取这一返回值，它的305-308行即判断年干支，重新比较month和day以确定在哪一年。

**Comment by fztransit** [comment]
如果你想改为从立春纪年。就在PerpetualCalendar.py中找到305行：nian = year。
删除其下一行：if month < 3 and yuefen.index(ym.split('闰')[-1]) >= 10: nian -= 1。这是原判断阴历年的方法。
并在305行下添加以下几行：
	count1 = count2 = len(jqrq)
	for i in range(count1):
		if jqrq[i][1] < 3: count1 -= 1
		if jqrq[i][1] == 3 and day < jqrq[i][0]: count2 -= 1
	if count1 == 0: nian -= 1  
	elif count2 != len(jqrq): nian -= 1  
这是从立春纪年的方法。
我已经在更新的代码中以注释形式给出。

**Comment by sufeiking** [comment]
New code works
